#[derive(Debug, PartialEq, Eq)]
struct Score {
    // TODO ?
}

impl std::fmt::Display for Score {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        todo!()
    }
}

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
enum Player {
    P1,
    P2,
}

#[derive(Debug, PartialEq, Eq)]
enum IncResult {
    Continue(Score),
    Winner(Player),
}

impl Score {
    pub fn new() -> Self {
        todo!()
    }
    pub fn point(self, p: Player) -> IncResult {
        todo!()
    }
}

#[cfg(test)]
mod test {
    #[test]
    fn scoring() {
        use super::Player;
        use super::Player::*;
        let tests: &[Vec<(Player, &str)>] = &[
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P1, "40-15"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P2, "0-40"),
                (P1, "15-40"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
                (P1, "winner 1"),
            ],
            vec![(P1, "15-0"), (P1, "30-0"), (P1, "40-0"), (P1, "winner 1")],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P1, "40-15"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P2, "15-40"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P1, "40-0"),
                (P2, "40-15"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P1, "40-0"),
                (P2, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![(P2, "0-15"), (P2, "0-30"), (P2, "0-40"), (P2, "winner 2")],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P2, "15-40"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P2, "15-40"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P2, "0-40"),
                (P1, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P1, "40-0"),
                (P2, "40-15"),
                (P2, "40-30"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P2, "winner 2"),
            ],
            vec![(P2, "0-15")],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P2, "0-40"),
                (P1, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![(P1, "15-0"), (P1, "30-0"), (P2, "30-15"), (P2, "30-30")],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![(P1, "15-0"), (P1, "30-0"), (P2, "30-15")],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P2, "0-40"),
                (P1, "15-40"),
                (P1, "30-40"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
                (P1, "winner 1"),
            ],
            vec![(P1, "15-0"), (P1, "30-0"), (P2, "30-15"), (P1, "40-15")],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![(P1, "15-0")],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P1, "40-0"),
                (P2, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![(P1, "15-0"), (P1, "30-0"), (P1, "40-0")],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![(P1, "15-0"), (P2, "15-15"), (P1, "30-15"), (P2, "30-30")],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P1, "40-15"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
            ],
            vec![(P2, "0-15"), (P2, "0-30"), (P2, "0-40")],
            vec![(P1, "15-0"), (P2, "15-15"), (P2, "15-30"), (P1, "30-30")],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P1, "40-0"),
                (P2, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P1, "40-0"),
                (P2, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P2, "0-40"),
                (P1, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P2, "0-40"),
                (P1, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![(P2, "0-15"), (P1, "15-15"), (P2, "15-30")],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
            ],
            vec![(P2, "0-15"), (P2, "0-30")],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P2, "0-40"),
                (P1, "15-40"),
                (P1, "30-40"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
            ],
            vec![(P1, "15-0"), (P1, "30-0")],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P1, "40-0"),
                (P2, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P1, "40-0"),
                (P2, "40-15"),
                (P2, "40-30"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![(P1, "15-0"), (P2, "15-15")],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P1, "40-0"),
                (P2, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P1, "40-0"),
                (P2, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![(P1, "15-0"), (P2, "15-15"), (P2, "15-30")],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![(P1, "15-0"), (P2, "15-15"), (P1, "30-15")],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![(P2, "0-15"), (P2, "0-30"), (P1, "15-30")],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![(P1, "15-0"), (P1, "30-0"), (P1, "40-0"), (P2, "40-15")],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P1, "40-0"),
                (P2, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P1, "40-0"),
                (P2, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P2, "0-40"),
                (P1, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P1, "40-0"),
                (P2, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P2, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P1, "30-0"),
                (P2, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P1, "40-15"),
                (P2, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![(P1, "15-0"), (P2, "15-15"), (P2, "15-30"), (P2, "15-40")],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P1, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P2, "0-30"),
                (P2, "0-40"),
                (P1, "15-40"),
                (P1, "30-40"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P1, "30-15"),
                (P2, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P1, "15-0"),
                (P2, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P1, "winner 1"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P1, "40-30"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
            vec![
                (P2, "0-15"),
                (P1, "15-15"),
                (P2, "15-30"),
                (P1, "30-30"),
                (P2, "30-40"),
                (P1, "deuce"),
                (P2, "advantage 2"),
                (P1, "deuce"),
                (P1, "advantage 1"),
                (P2, "deuce"),
                (P2, "advantage 2"),
                (P2, "winner 2"),
            ],
        ];
        for test in tests {
            let mut score = super::Score::new();
            assert_eq!(format!("{score}"), "0-0");
            for (player, expected) in test {
                match score.point(*player) {
                    crate::tennis::IncResult::Continue(s) => {
                        score = s;
                        assert_eq!(format!("{score}"), *expected);
                    }
                    crate::tennis::IncResult::Winner(w) => {
                        assert_eq!(
                            match w {
                                P1 => "winner 1",
                                P2 => "winner 2",
                            },
                            *expected
                        );
                        break;
                    }
                }
            }
        }
    }
}
